import type { InventoryPreviewLayout } from "./codyTypes";

export const INVENTORY_PREVIEW_LAYOUT: Record<string, InventoryPreviewLayout> =
  {
    "hair_1-1": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-50 h-75",
      mobileOffset: "-160px",
      desktopOffset: "-60px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "0px",
    },
    "hair_1-2": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-35 h-30",
      mobileOffset: "-152px",
      desktopOffset: "-50px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-5px",
    },
    "hair_1-3": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-30 h-30",
      mobileOffset: "-154px",
      desktopOffset: "-60px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-5px",
    },
    "hair_1-4": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-30 h-30",
      mobileOffset: "-152px",
      desktopOffset: "-50px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-5px",
    },
    "hair_1-5": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-40 h-55",
      mobileOffset: "-156px",
      desktopOffset: "-55px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-10px",
    },
    "hair_1-6": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-30 h-30",
      mobileOffset: "-146px",
      desktopOffset: "-50px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-15px",
    },
    top_1: {
      mobileCard: "w-24 h-36",
      desktopCard: "w-68 h-35",
      mobileOffset: "-198px",
      desktopOffset: "-140px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "15px",
    },
    skirt_1: {
      mobileCard: "w-24 h-36",
      desktopCard: "w-68 h-65",
      mobileOffset: "-222px",
      desktopOffset: "-220px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-20px",
    },
    dress_1: {
      mobileCard: "w-24 h-36",
      desktopCard: "w-35 h-55",
      mobileOffset: "-208px",
      desktopOffset: "-124px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-15px",
    },
    dress_2: {
      mobileCard: "w-24 h-36",
      desktopCard: "w-45 h-55",
      mobileOffset: "-214px",
      desktopOffset: "-135px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-10px",
    },
    dress_3: {
      mobileCard: "w-24 h-36",
      desktopCard: "w-70 h-85",
      mobileOffset: "-210px",
      desktopOffset: "-140px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-15px",
    },
    dress_4: {
      mobileCard: "w-24 h-36",
      desktopCard: "w-60 h-65",
      mobileOffset: "-206px",
      desktopOffset: "-140px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "10px",
    },
    dress_5: {
      mobileCard: "w-24 h-36",
      desktopCard: "w-55 h-55",
      mobileOffset: "-212px",
      desktopOffset: "-135px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "15px",
    },
    jacket_1: {
      mobileCard: "w-24 h-36",
      desktopCard: "w-50 h-70",
      mobileOffset: "-175px",
      desktopOffset: "-50px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-5px",
    },
    shoes_1: {
      mobileCard: "w-28 h-28",
      desktopCard: "w-30 h-45",
      mobileOffset: "-425px",
      desktopOffset: "-475px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "10px",
    },
    shoes_2: {
      mobileCard: "w-28 h-28",
      desktopCard: "w-25 h-35",
      mobileOffset: "-425px",
      desktopOffset: "-510px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "15px",
    },
    shoes_3: {
      mobileCard: "w-28 h-28",
      desktopCard: "w-30 h-52",
      mobileOffset: "-425px",
      desktopOffset: "-450px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "5px",
    },
    shoes_4: {
      mobileCard: "w-28 h-28",
      desktopCard: "w-25 h-40",
      mobileOffset: "-425px",
      desktopOffset: "-500px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "0px",
    },
    shoes_5: {
      mobileCard: "w-28 h-28",
      desktopCard: "w-20 h-25",
      mobileOffset: "-425px",
      desktopOffset: "-550px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "0px",
    },
    "deco_1-1": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-20 h-20",
      mobileOffset: "-150px",
      desktopOffset: "-140px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "0px",
    },
    "deco_1-2": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-20 h-20",
      mobileOffset: "-175px",
      desktopOffset: "-175px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "0px",
    },
    "deco_2-1": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-25 h-20",
      mobileOffset: "-180px",
      desktopOffset: "-180px",
      mobileLeftOffset: "100px",
      desktopLeftOffset: "150px",
    },
    "deco_2-2": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-28 h-28",
      mobileOffset: "-152px",
      desktopOffset: "-160px",
      mobileLeftOffset: "50px",
      desktopLeftOffset: "120px",
    },
    "deco_7-1": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-28 h-28",
      mobileOffset: "-156px",
      desktopOffset: "-176px",
      mobileLeftOffset: "-50px",
      desktopLeftOffset: "-100px",
    },
    "deco_3-1": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-10 h-20",
      mobileOffset: "-158px",
      desktopOffset: "-70px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "30px",
    },
    "deco_3-2": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-10 h-15",
      mobileOffset: "-144px",
      desktopOffset: "-45px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "-25px",
    },
    "deco_3-3": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-20 h-10",
      mobileOffset: "-156px",
      desktopOffset: "-60px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "0px",
    },
    "deco_4-1": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-50 h-90",
      mobileOffset: "-230px",
      desktopOffset: "-190px",
      mobileLeftOffset: "-30px",
      desktopLeftOffset: "-60px",
    },
    "deco_4-2": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-40 h-60",
      mobileOffset: "-230px",
      desktopOffset: "-200px",
      mobileLeftOffset: "-30px",
      desktopLeftOffset: "-60px",
    },
    "deco_5-1": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-10 h-30",
      mobileOffset: "-175px",
      desktopOffset: "-200px",
      mobileLeftOffset: "-15px",
      desktopLeftOffset: "-30px",
    },
    "deco_6-1": {
      mobileCard: "w-28 h-40",
      desktopCard: "w-30 h-10",
      mobileOffset: "-300px",
      desktopOffset: "-425px",
      mobileLeftOffset: "0px",
      desktopLeftOffset: "15px",
    },
  };

export const getInventoryPreviewLayout = (
  itemId: string,
): InventoryPreviewLayout => {
  const layout = INVENTORY_PREVIEW_LAYOUT[itemId];

  if (!layout) {
    throw new Error(`Missing inventory preview layout for item: ${itemId}`);
  }

  return layout;
};
